//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jinx.J003.UpdateDoubanSubject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Douban_Movie_Info
    {
        public string ID { get; set; }
        public string Title { get; set; }
        public string Title_Original { get; set; }
        public string Title_Aka { get; set; }
        public string Year { get; set; }
        public string Image { get; set; }
        public string Directors { get; set; }
        public string Writers { get; set; }
        public string Casts { get; set; }
        public string Genres { get; set; }
        public string Countries { get; set; }
        public string Website { get; set; }
        public string Languages { get; set; }
        public string Pubdates { get; set; }
        public string Durations { get; set; }
        public string IMDb { get; set; }
        public string Summary { get; set; }
        public string Rating { get; set; }
        public Nullable<int> Rating_Count { get; set; }
        public string Star_5 { get; set; }
        public string Star_4 { get; set; }
        public string Star_3 { get; set; }
        public string Star_2 { get; set; }
        public string Star_1 { get; set; }
        public string Seasons_Count { get; set; }
        public string Current_Season { get; set; }
        public string Episodes_Count { get; set; }
    }
}
