//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jinx.J003.UpdateDoubanSubject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Douban_Celebrity_Info
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Name_Original { get; set; }
        public string Image { get; set; }
        public string Gender { get; set; }
        public string Constellation { get; set; }
        public string Day_Birth { get; set; }
        public string Day_Death { get; set; }
        public string Born_Place { get; set; }
        public string Profession { get; set; }
        public string Name_Aka { get; set; }
        public string Name_Aka_Original { get; set; }
        public string Family_Member { get; set; }
        public string IMDb { get; set; }
        public string Website { get; set; }
        public string Summary { get; set; }
    }
}
