//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jinx.J003.UpdateDoubanSubject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Douban_Movie_Popular
    {
        public System.Guid PID { get; set; }
        public string ID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string Rate { get; set; }
        public string Cover { get; set; }
        public Nullable<int> Cover_X { get; set; }
        public Nullable<int> Cover_Y { get; set; }
        public Nullable<bool> Playable { get; set; }
        public Nullable<bool> Is_New { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
