//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jinx.J003.UpdateDoubanSubject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Douban_Movie_ID
    {
        public int ID { get; set; }
        public Nullable<bool> Initialized { get; set; }
        public Nullable<bool> Read { get; set; }
        public Nullable<bool> FZF { get; set; }
        public Nullable<int> Rating_Count { get; set; }
        public string Directors { get; set; }
        public string Writers { get; set; }
        public string Casts { get; set; }
        public Nullable<bool> Split { get; set; }
        public Nullable<bool> Collection { get; set; }
    }
}
