//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jinx.J003.UpdateDoubanSubject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Store
    {
        public int ID { get; set; }
        public string SubjectID { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
        public Nullable<double> Size { get; set; }
        public string Drive { get; set; }
    }
}
